### PR TITLE
coretext: implement GetFallbackFunc

### PR DESCRIPTION
**Pull request by pigoz**
I used the font family contained in ASS_FontProviderMetaData to create the font we are falling back from. I can switch to an hardcoded Arial if needed.

### CODE REVIEW

**Comment by grigorig** [comment]
LGTM, although I may want to kill/replace the "meta" parameter. Does this work with the testcase I sent earlier?

**Comment by wm4** [comment]
I can do this tomorrow.

I'll also merge this tomorrow.

**Comment by pigoz** [comment]
@grigorig forgot to mention there are two missing glyphs with the test case you sent
test

**Comment by grigorig** [comment]
It also seems strange that it uses the Comic font for the "Test" string. What is the debug output for this test case?

**Comment by pigoz** [comment]
That's because I changed the font family in the test script to Comic Sans
MS to see if it was working correctly.

**Comment by grigorig** [comment]
Maybe the missing glyphs are actually okay, possibly you are just lacking a font with those glyphs, or they are only available as bitmaps.

**Comment by pigoz** [comment]
Well the last one is rendered as as a bitmap emoji in other applications.. the middle one is not a bitmap but looks strange even in other applications.

**Comment by wm4** [comment]
Sounds good enough to me.

**Comment by wm4** [comment]
Merged.

We still have doubts about that CFStringCreateWithBytes call, though.

**Pull request closed without merging**
