### PR TITLE
Fix bunch of UB

### PR DESCRIPTION
**Pull request by MrSmile**
Fix potential problem found by Coverity Scan and couple of errors found by -fsanitize=undefined.

### CODE REVIEW

**Comment by astiob** [comment]
Upon more careful inspection, it seems `!current_info` is impossible at that point. Whenever we reach the `last_info = info;` line, we’ve already initialized `current_info` to a valid pointer.

**Comment by rcombs** [comment]
Maybe just `assert`, then? Unless there's some case we're missing (and I don't _think_ there is).

**Comment by astiob** [comment]
This check was added in 30004491d2dc3ab84520333b1e13c82a99aa081f, which already acknowledged it was impossible but added it anyway to guard against future code changes that might make it a possibility. The direct trigger for that commit was a warning from Clang’s static analyser, which presumably failed to recognize that `is_new_bm_run` would always return `true` until the variable was initialized. I don’t know if Clang can be taught about this (an `assert` might work), but in any case, I can see some appeal in guarding against future changes, since I think this isn’t immediately obvious to a human either.

**Comment by MrSmile** [comment]
I should add some comment about unreachable code to clarify that check then.

**Comment by astiob** [comment]
I also like the `assert` suggestion. \*shrugs\*

**Comment by rcombs** [comment]
The clang static analyzer respects assertions.

**Comment by MrSmile** [comment]
Does it treat `assert(ptr)` and `ptr->something` different? It's the same class of problem for me.

**Comment by rcombs** [comment]
If you `assert(ptr)` it assumes that `ptr` will always be non-null at that point.

**Comment by MrSmile** [comment]
Even with something totally wrong like `assert(2 + 2 = 5)`? Okay, I replace check with assert then.

**Comment by rcombs** [comment]
The way it actually works is that `assert(e)` is a macro defined like this:
```
#define assert(e) \
    (__builtin_expect(!(e), 0) ? __assert_rtn(__func__, __FILE__, __LINE__, #e) : (void)0)
```
and `__assert_rtn` is declared with `__attribute__((noreturn))`. So `assert(2 + 2 == 5)` is `assert(false)`, which is effectively equivalent to `abort();` from the static analyzer's perspective, so it'll assume that anything past it is unconditionally unreachable.

**Pull request merged**
