### PR TITLE
font: prefer full-Unicode cmaps to BMP-only ones

### PR DESCRIPTION
**Pull request by astiob**
Fixes: https://github.com/libass/libass/issues/634
Fixes: https://github.com/mpv-player/mpv/issues/13322

### CODE REVIEW

**Comment by astiob** [comment]
For reference, my (untested) understanding is that if the font has no Microsoft cmaps, our code already ends up using a full-Unicode non-Microsoft cmap if one exists or a less-full non-Microsoft Unicode cmap otherwise, because that’s what FreeType selects automatically upon opening the font face, and only if no Unicode cmap exists, does our last loop execute and select the first of all cmaps.

**Comment by rcombs** [comment]
Hmm, does this match the GDI behavior? At least in older Windows versions (XP), as far as I can tell, there was no special handling for format ID 10, and no preference was given between different encoding IDs at all (it just used the first Microsoft cmap, falling back on a Mac one with plat=1 enc=0 if none existed). Noto Emoji might get symbol-font treatment here since it has a panose familytype of 5 (pictoral) in its OS/2 table.

That said, regardless of GDI behavior, I'm 👍 on this change (it's hard to imagine it making anything *worse*, and clearly improves things for users here).

**Comment by astiob** [comment]
If you mean what I think you mean, there seems to be no support for encoding 10 or 6 (Johab) in that code at all, so it’s definitely outdated. At any rate, we know VSFilter does show supplementary-plane characters, and it couldn’t do it without encoding 10.

But I’ve just run a dedicated test, and it’s… weird. VSFilter doesn’t use the Noto Emoji glyph from #634, substituting it by what looks like the glyph from Segoe UI Emoji (but does use base ASCII glyphs from Noto Emoji). But Segoe UI Emoji is itself affected by this cmap issue (and works fine in VSFilter), and the FiraCode sample from mpv also works in VSFilter.

**Review by TheOneric — APPROVED** [review]
Makes sense to me, code looks good and I can confirm it fixes the two linked samples (in `compare`).

I don’t know what exactly GDI/VSFilter does, but since it appear to use UCS-4 cmap at least most of the time, this change should also be an improvement i this regard.

> For reference, my (untested) understanding is that if the font has no Microsoft cmaps, our code already ends up using a full-Unicode non-Microsoft cmap if one exists or a less-full non-Microsoft Unicode cmap otherwise, because that’s what FreeType selects automatically upon opening the font face

I couldn’t find this being promised in the docs, but indeed FreeType’s code currently [calls `find_unicode_charmap` in `open_face`](https://gitlab.freedesktop.org/freetype/freetype/-/blob/57617782464411201ce7bbc93b086c1b4d7d84a5/src/base/ftobjs.c#L1569)  which [tries to select](https://gitlab.freedesktop.org/freetype/freetype/-/blob/57617782464411201ce7bbc93b086c1b4d7d84a5/src/base/ftobjs.c#L1410) a full-range Unicode map of either Microsoft or Apple platform encoding or if no such exists any Unicode encoding cmap.

**Comment by astiob** [comment]
> I couldn’t find this being promised in the docs, but indeed FreeType’s code currently [calls `find_unicode_charmap` in `open_face`](https://gitlab.freedesktop.org/freetype/freetype/-/blob/57617782464411201ce7bbc93b086c1b4d7d84a5/src/base/ftobjs.c#L1569) which [tries to select](https://gitlab.freedesktop.org/freetype/freetype/-/blob/57617782464411201ce7bbc93b086c1b4d7d84a5/src/base/ftobjs.c#L1410) a full-range Unicode map of either Microsoft or Apple platform encoding or if no such exists any Unicode encoding cmap.

Yup, this is exactly my own main reference. But this is somewhat documented, too:

* [The doc for `FT_Select_Charmap`](https://freetype.org/freetype2/docs/reference/ft2-character_mapping.html#ft_select_charmap) says it selects the fullest Unicode cmap when asked for Unicode.
* [The doc for `FT_CharMap`](https://freetype.org/freetype2/docs/reference/ft2-character_mapping.html#ft_charmap) says newly created faces select a Unicode cmap automatically.

**Comment by ahaoboy** [comment]
After testing, this fix can render 0xF0411 correctly. Place the font file in compare/test/FiraCodeNerdFont-Regular.ttf and modify the font name and rendering text in sub1.ass.

```ass
[Script Info]
PlayResX: 320
PlayResY: 240
ScaledBorderAndShadow: yes

[V4+ Styles]
Format: Name, Fontname, Fontsize, PrimaryColour, SecondaryColour, OutlineColour, BackColour, Bold, Italic, Underline, StrikeOut, ScaleX, ScaleY, Spacing, Angle, BorderStyle, Outline, Shadow, Alignment, MarginL, MarginR, MarginV, Encoding
Style: Default,FiraCode Nerd Font Reg,200,&H000000FF,&H000000FF,&H00000000,&H00000000,0,0,0,0,100,100,0,0,1,8,0,5,10,10,10,1

[Events]
Format: Layer, Start, End, Style, Name, MarginL, MarginR, MarginV, Effect, Text
Dialogue: 0,0:00:00.00,0:00:04.00,Default,,0,0,0,,{\t(\frz+180)}󰐑

```
[FiraCodeNerdFont-Regular.zip](https://github.com/libass/libass/files/13999705/FiraCodeNerdFont-Regular.zip)

Branch master
```
Loading font 'FiraCodeNerdFont-Regular.ttf'.
Loading font 'font1.ttf'.
Loading font 'font2.otf'.
Processing 'sub1.ass':
  Time 0:00:00.500 - libass: fontselect: failed to find any fallback with glyph 0xF0411 for font: (FiraCode Nerd Font Reg, 400, 0)
255.000 FAIL
  Time 0:00:01.500 - libass: fontselect: failed to find any fallback with glyph 0xF0411 for font: (FiraCode Nerd Font Reg, 400, 0)
255.000 FAIL
  Time 0:00:02.500 - libass: fontselect: failed to find any fallback with glyph 0xF0411 for font: (FiraCode Nerd Font Reg, 400, 0)
255.000 FAIL
Processing 'sub2.ass':
  Time 0:02:33.000 - 0.728 GOOD
Only 1 of 4 images have passed test (BAD or better)
```
image


Branch full-unicode-cmap
```
Loading font 'FiraCodeNerdFont-Regular.ttf'.
Loading font 'font1 copy.ttf'.
Loading font 'font1.ttf'.
Loading font 'font2.otf'.
Processing 'sub1.ass':
  Time 0:00:00.500 - 255.000 FAIL
  Time 0:00:01.500 - 255.000 FAIL
  Time 0:00:02.500 - 255.000 FAIL
Processing 'sub2.ass':
  Time 0:02:33.000 - 0.728 GOOD
Only 1 of 4 images have passed test (BAD or better)
```
image

**Pull request merged**
