### PR TITLE
fix my issue

### PR DESCRIPTION
**Pull request by pingplug**
I tried to fix issue #154  
It seems work

### CODE REVIEW

**Comment by wm4** [comment]
>change default ScaledBorderAndShadow to 1

I support this, even if it's not "compatible".

**Comment by rcombs** [comment]
Just was looking at vsfilter source to see, and it's not, and whether we think it's a good idea in general or not, I find it weird to be regressing in a compatibility as part of a fix for a compatibility issue.

**Comment by wm4** [comment]
Looking at the commit, your changes actually _disable_ ScaledBorderAndShadow, which conflicts with what the commit message says.

**Comment by wm4** [comment]
Also be aware that you must call ``ass_set_storage_size()`` to the size of the video. (This can be a different value from ``ass_set_frame_size()`` if the subtitles are rendered into a video frame that has already be scaled, like for rendering in display resolution in a video player.)

**Comment by pingplug** [comment]
sorry, I almost forgot this...
about the commit message... it's a typo
about the second one... in my MPC-HC, the space between texts is the same even the video is scaled (it's realy odd)

**Comment by grigorig** [comment]
Yes, ScaledBorderAndShadow=1 may be a more sensible default. Can you explain the second commit a bit better, ideally in the commit message?

**Comment by pingplug** [comment]
@grigorig 
If you put two collision texts with more than one line, the space between two texts is closer than the lines in the same text in libass
VSFilter add borders(top/bottom, = max border_y of the top/bottom line) between texts, when placing collision texts, the borders make a proper space between two texts

sorry for my poor english :P

**Comment by pingplug** [comment]
rewrite commit message
commit 1 disable the ScaledBorderAndShadow by default like VSFilter does
dummy_000_0
before
dummy_001_0
after

commit 2 add a border between two collision texts, makes the space between two collision texts larger than space between two lines, Which is what VSFilter does.
dummy_002_0

ass file:
```
[V4+ Styles]
Format: Name, Fontname, Fontsize, PrimaryColour, SecondaryColour, OutlineColour, BackColour, Bold, Italic, Underline, StrikeOut, ScaleX, ScaleY, Spacing, Angle, BorderStyle, Outline, Shadow, Alignment, MarginL, MarginR, MarginV, Encoding
Style: Default,微软雅黑,31,&H00FFFFFF,&H00000000,&H00000000,&H00000000,-1,0,0,0,100,100,0,0,1,1,0,2,30,30,15,1

[Events]
Format: Layer, Start, End, Style, Name, MarginL, MarginR, MarginV, Effect, Text
Dialogue: 0,0:00:00.00,0:00:27.16,*Default,NTP,0,0,0,,Text1, line1 测试\NText1, line2 测试
Dialogue: 0,0:00:00.00,0:00:27.16,*Default,NTP,0,0,0,,Text2, line1 测试\NText2, line2 测试
```

**Comment by wm4** [comment]
It's still not clear whether whatever code you use calls ``ass_set_storage_size()``.

I don't know whether changing the ``ScaledBorderAndShadow`` default is reasonable; it used not to make any sense with libass (because libass could render to screen resolution, i.e. different frame size than the video frame), but maybe the storage size thing handles this correctly now.

**Comment by pingplug** [comment]
@wm4  there are may subtitles uses the default resolution 484x480, but the resolution of video is much more higher(1920x1080). These subtitles are created and previewed with VSFilter, and the border is not scaled. libass will scale the border, make the border thicker than VSFilter.

**Comment by wm4** [comment]
That's yet another issue, and not what I asked about.

**Comment by pingplug** [comment]
`ass_set_storage_size()` will not change the value of `ScaledBorderAndShadow`, so I don't think this function can help

**Comment by TheOneric** [comment]
The two issues this pr attempted to resolve have since been addressed by #390 and #395 .

**Pull request closed without merging**
