### PR TITLE
Fix buffer overrun in rasterizer

### PR DESCRIPTION
**Pull request by MrSmile**
Found buffer overrun (since assembly overhaul, I think) in rasterizer, but instead of an easy fix decided to go the long way and complete longstanding TODO.

### CODE REVIEW

**Comment by astiob** [comment]
May I ask a stupid question?

My intuitive understanding of tiled rendering is that tiles are disjoint rectangles of whole pixels. Why should there be any difference, then, whether addition or max is used to combine them?

**Comment by MrSmile** [comment]
It's about mechanism to combat different winding direction: I'm generating two different border outlines with positive and negative offset, rasterize them independently and then blend. That final blending should be max-blending and not addition.

**Review by astiob — APPROVED** [review]
Ah, that thing! Right. LGTM (including the new commit).

**Comment by astiob** [comment]
Ah: could you perhaps clarify just how big the buffer overrun was, and whether it was read-only or write as well?

**Review by TheOneric — APPROVED** [review]

**Pull request merged**
