### PR TITLE
x86: update x86inc.asm

### PR DESCRIPTION
**Pull request by loqs**
Updated to https://code.videolan.org/videolan/x86inc.asm/-/commit/04f14f431ce07ca349b5d87c9e5930f5950cf712

Related https://github.com/libass/libass/issues/742

### CODE REVIEW

**Comment by TheOneric** [comment]
I can confirm [c398563](https://github.com/libass/libass/pull/743/commits/c398563bc6d17ba831d8db76b7f523b2fd3a8b3d) updates to the claimed upstream version and checks still pass in all three x86 flavours (see [test logs](https://github.com/libass/libass-tests/actions/runs/8511432538)).  
I’m unable to test the shadowstack and IBT features which motivated this upgrade though

---

Side note: while testing I also noticed two pre-existing warnings/issues for ix86 and x32:

On x32 we apparently build with an executable stack for some reason *(both `libass.so` and `checkasm`)*:
```
/usr/bin/ld: warning: libass/x86/.libs/cpuid.o: missing .note.GNU-stack section implies executable stack
/usr/bin/ld: NOTE: This behaviour is deprecated and will be removed in a future version of the linker
```


On ix86 we default to non-PIC as usual, but even with `--with-pic` set, checkasm itself isn’t PIC compatible, so even with `--with-pic` `checkasm` won’t be PIC/PIE and thus refuse to work with default settings on e.g. Alpine *(apart from warnings it works fine in our own, Debian-based CI)*. This is inconvenient for packagers wishing to run tests, but I’m not sure we can do anything reasonable about it.
```
/usr/lib/gcc/i586-alpine-linux-musl/13.2.1/../../../../i586-alpine-linux-musl/bin/ld: checkasm/x86/checkasm.o: warning: relocation in read-only section `.text'
/usr/lib/gcc/i586-alpine-linux-musl/13.2.1/../../../../i586-alpine-linux-musl/bin/ld: warning: creating DT_TEXTREL in a PIE
```

**Comment by loqs** [comment]
The presence of `.note.gnu.property` indicating support for shadow stack on elf X86_64 can be verified with:
```
 readelf -n /usr/lib/libass.so.9.2.1 

Displaying notes found in: .note.gnu.property
  Owner                Data size 	Description
  GNU                  0x00000010	NT_GNU_PROPERTY_TYPE_0
      Properties: x86 feature: SHSTK

Displaying notes found in: .note.gnu.build-id
  Owner                Data size 	Description
  GNU                  0x00000014	NT_GNU_BUILD_ID (unique build ID bitstring)
    Build ID: 941659e4f95916479bf608c3e47531029ae05d3c
```
```
LDFLAGS=' -Wl,-z,cet-report=error'
/usr/bin/ld: libass/x86/.libs/rasterizer.o: error: missing IBT property
/usr/bin/ld: libass/x86/.libs/blend_bitmaps.o: error: missing IBT property
/usr/bin/ld: libass/x86/.libs/be_blur.o: error: missing IBT property
/usr/bin/ld: libass/x86/.libs/blur.o: error: missing IBT property
/usr/bin/ld: libass/x86/.libs/cpuid.o: error: missing IBT property
```
`GLIBC_TUNABLES=glibc.cpu.hwcaps=SHSTK make check` exits with no error. Are there any other tests you would like me to carry out?

**Comment by TheOneric** [comment]
> `GLIBC_TUNABLES=glibc.cpu.hwcaps=SHSTK make check` exits with no error

Assuming you did that on a system with new enough glibc, this seems good thx.
You probably only ran the `checkasm` tests though. We have more tests which should run all parts of the code, but for various reasons their samples are in a different repo. To run those you’ll need to clone https://github.com/libass/libass-tests somewhere and configure libass with `--enable-fuzz --enable-compare ART_SAMPLES=<path to root of test repo>`.
Rebuilding and running `make check` again will then run everything.
Could you repeat it with the full test set?

In #742 it was mentioned, Windows 11 also supports (some?) CET features, but I don’t immediately spot any relevant Windows changes in the diff. Does this mean x86inc currently doesn’t support CET on Windows yet, or can it be enabled without x86inc changes here and we should also test Windows already?

Btw, why did you mark this PR as a draft?

**Comment by loqs** [comment]
> Btw, why did you mark this PR as a draft?

Lack of confidence/inexperience. I was looking for an option to ask you to review it and not immediately merge it.

**Comment by Gramner** [comment]
> On ix86 we default to non-PIC as usual, but even with `--with-pic` set, checkasm itself isn’t PIC compatible, so even with `--with-pic` `checkasm` won’t be PIC/PIE and thus refuse to work with default settings on e.g. Alpine _(apart from warnings it works fine in our own, Debian-based CI)_. This is inconvenient for packagers wishing to run tests, but I’m not sure we can do anything reasonable about it.
> 
> ```
> /usr/lib/gcc/i586-alpine-linux-musl/13.2.1/../../../../i586-alpine-linux-musl/bin/ld: checkasm/x86/checkasm.o: warning: relocation in read-only section `.text'
> /usr/lib/gcc/i586-alpine-linux-musl/13.2.1/../../../../i586-alpine-linux-musl/bin/ld: warning: creating DT_TEXTREL in a PIE
> ```

I'm pretty sure `checkasm` is supposed to be PIC-compliant even on 32-bit x86 if `PIC` is defined to 1 in the nasm invocation, e.g. through `-DPIC=1` or similar.

**Comment by Gramner** [comment]
> In #742 it was mentioned, Windows 11 also supports (some?) CET features, but I don’t immediately spot any relevant Windows changes in the diff. Does this mean x86inc currently doesn’t support CET on Windows yet, or can it be enabled without x86inc changes here and we should also test Windows already?

CET on Windows is handled purely through linker flags, there are no flags in individual object files.

**Comment by TheOneric** [comment]
friendly ping on this

> > `GLIBC_TUNABLES=glibc.cpu.hwcaps=SHSTK make check` exits with no error
>
> [...]
> We have more tests which should run all parts of the code, but for various reasons their samples are in a different repo. To run those you’ll need to clone https://github.com/libass/libass-tests somewhere and configure libass with `--enable-fuzz --enable-compare ART_SAMPLES=<path to root of test repo>`.
Rebuilding and running make check again will then run everything.
Could you repeat it with the full test set?

**Comment by loqs** [comment]
```
$ GLIBC_TUNABLES=glibc.cpu.hwcaps=SHSTK make check
make  checkasm/checkasm
make[1]: Entering directory '/build/libass/src/libass'
[CRASH-TEST]: ./generic.ass
[TEST]: ./draw-images
OK.

[CRASH-TEST]: ./aegisub-format-tests.ass
  CC       checkasm/checkasm-blend_bitmaps.o
  CC       checkasm/checkasm-rasterizer.o
  CC       checkasm/checkasm-blur.o
  CC       checkasm/checkasm-be_blur.o
  CC       checkasm/checkasm-checkasm.o
  NASM     checkasm/x86/checkasm.o
OK.

All tests passed!
Loading font 'Arimo-Regular.ttf'.
Processing 'drawImg.ass':
  Time 0:01:44.396 - 0.000 SAME
All 1 images have passed test (BAD or better)

[TEST]: ./font_nonunicode
  CCLD     checkasm/checkasm
Loading font 'shiftjis_Reishoreiryu.ttf'.
Loading font 'big5-hkscs_SingYi-Ultra.ttf'.
Processing 'big5-hkscs.ass':
  Time 0:00:01.000 - 0.000 SAME
Processing 'shiftjis.ass':
  Time 0:00:01.000 - 0.000 SAME
All 2 images have passed test (BAD or better)

[TEST]: ./token-parsing
Loading font 'DejaVuSans.ttf'.
Processing 'trimming.ass':
  Time 0:00:00.000 - 0.000 SAME
All 1 images have passed test (BAD or better)

[TEST]: ./ssa
Loading font 'DejaVuSans.ttf'.
Processing 'alpha.ass':
  Time 0:00:00.000 - 0.000 SAME
  Time 0:00:01.000 - 0.000 SAME
  Time 0:00:02.000 - 0.000 SAME
  Time 0:00:03.000 - 0.000 SAME
  Time 0:00:04.000 - 0.000 SAME
Processing 'effect-delay.ass':
  Time 0:00:00.600 - 0.000 SAME
  Time 0:00:01.600 - 0.000 SAME
  Time 0:00:02.600 - 0.000 SAME
  Time 0:00:03.960 - 0.000 SAME
  Time 0:00:04.960 - 0.000 SAME
  Time 0:00:05.960 - 0.000 SAME
All 11 images have passed test (BAD or better)

[TEST]: ./vsf-quirks-var
Loading font 'DejaVuSans.ttf'.
Processing 'alpha-clipping.ass':
  Time 0:00:02.040 - 0.000 SAME
  Time 0:00:02.560 - 0.000 SAME
  Time 0:00:04.960 - 0.000 SAME
All 3 images have passed test (BAD or better)

[TEST]: ./zero-area
Loading font 'DejaVuSans.ttf'.
Processing 'zero-area.ass':
  Time 0:00:02.000 - 0.000 SAME
  Time 0:00:08.000 - 0.000 SAME
All 2 images have passed test (BAD or better)

[TEST]: ./blurs
Loading font 'Aileron-Regular.otf'.
Processing 'be.ass':
  Time 0:00:00.500 - 0.000 SAME
  Time 0:00:01.500 - 0.000 SAME
  Time 0:00:02.500 - 0.000 SAME
  Time 0:00:03.500 - 0.000 SAME
Processing 'blur+t.ass':
  Time 0:00:01.000 - 0.000 SAME
  Time 0:00:01.100 - 0.000 SAME
  Time 0:00:01.200 - 0.000 SAME
  Time 0:00:01.300 - 0.000 SAME
  Time 0:00:01.400 - 0.000 SAME
  Time 0:00:01.500 - 0.000 SAME
  Time 0:00:01.600 - 0.000 SAME
  Time 0:00:01.700 - 0.000 SAME
  Time 0:00:01.800 - 0.000 SAME
  Time 0:00:01.900 - 0.000 SAME
All 14 images have passed test (BAD or better)

[TEST]: ./karaoke
Loading font 'Arimo-Regular.ttf'.
Loading font 'Arimo-Bold.ttf'.
Loading font 'IPAexGothic.ttf'.
Processing '216-vertical.ass':
  Time 0:00:02.252 - 0.000 SAME
Processing '357-k-and-kf-desynced.ass':
  Time 0:00:06.798 - 0.000 SAME
  Time 0:00:07.170 - 0.000 SAME
  Time 0:00:08.170 - 0.000 SAME
Processing 'karaoke-and-runsplits.ass':
  Time 0:00:00.000 - 0.000 SAME
  Time 0:00:02.040 - 0.000 SAME
  Time 0:00:02.800 - 0.000 SAME
  Time 0:00:03.120 - 0.000 SAME
  Time 0:00:04.600 - 0.000 SAME
All 9 images have passed test (BAD or better)

[TEST]: ./implicit-pos
Loading font 'DejaVuSans.ttf'.
Processing 'bordercollision.ass':
  Time 0:00:02.000 - 0.000 SAME
Processing 'shift-dir.ass':
  Time 0:00:00.500 - 0.000 SAME
  Time 0:00:01.500 - 0.000 SAME
  Time 0:00:02.500 - 0.000 SAME
  Time 0:00:03.500 - 0.000 SAME
  Time 0:00:04.500 - 0.000 SAME
  Time 0:00:05.500 - 0.000 SAME
  Time 0:00:06.500 - 0.000 SAME
  Time 0:00:07.500 - 0.000 SAME
  Time 0:00:08.500 - 0.000 SAME
  Time 0:00:09.500 - 0.000 SAME
All 11 images have passed test (BAD or better)

[TEST]: ./scaling_playres
Loading font 'DejaVuSans.ttf'.
Processing 'playresx_sbas-no.ass':
  Time 0:00:00.000 - 0.000 SAME
  Time 0:00:01.000 - 0.000 SAME
  Time 0:00:02.000 - 0.000 SAME
Processing 'playresx_sbas-yes.ass':
  Time 0:00:00.000 - 0.000 SAME
  Time 0:00:01.000 - 0.000 SAME
  Time 0:00:02.000 - 0.000 SAME
  Time 0:00:03.000 - 0.000 SAME
  Time 0:00:04.000 - 0.000 SAME
All 8 images have passed test (BAD or better)

[TEST]: ./v4++
Loading font 'DejaVuSans.ttf'.
Processing 'kt.ass':
  Time 0:00:01.000 - 0.000 SAME
  Time 0:00:01.500 - 0.000 SAME
  Time 0:00:02.000 - 0.000 SAME
  Time 0:00:02.480 - 0.000 SAME
  Time 0:00:03.000 - 0.000 SAME
  Time 0:00:03.600 - 0.000 SAME
  Time 0:00:04.000 - 0.000 SAME
  Time 0:00:04.500 - 0.000 SAME
  Time 0:00:04.800 - 0.000 SAME
  Time 0:00:05.100 - 0.000 SAME
  Time 0:00:05.199 - 0.000 SAME
  Time 0:00:05.200 - 0.000 SAME
  Time 0:00:05.280 - 0.000 SAME
  Time 0:00:06.000 - 0.000 SAME
  Time 0:00:06.700 - 0.000 SAME
  Time 0:00:07.120 - 0.000 SAME
  Time 0:00:08.000 - 0.000 SAME
  Time 0:00:08.640 - 0.000 SAME
  Time 0:00:08.920 - 0.000 SAME
  Time 0:00:08.960 - 0.000 SAME
  Time 0:00:09.000 - 0.000 SAME
  Time 0:00:10.000 - 0.000 SAME
  Time 0:00:10.480 - 0.000 SAME
  Time 0:00:11.000 - 0.000 SAME
  Time 0:00:11.870 - 0.000 SAME
All 25 images have passed test (BAD or better)

[TEST]: ./blurs-anamorphic
Loading font 'Aileron-Regular.otf'.
Processing 'blur.ass':
  Time 0:00:00.000 - 0.000 SAME
All 1 images have passed test (BAD or better)

[TEST]: ./embedded-font
Processing 'efont.ass':
  Time 0:00:01.000 - 0.000 SAME
All 1 images have passed test (BAD or better)

[TEST]: ./scaled-border-default
make[1]: Leaving directory '/build/libass/src/libass'
make  check-TESTS
make[1]: Entering directory '/build/libass/src/libass'
libass: Neither PlayResX nor PlayResY defined. Assuming 384x288
make[2]: Entering directory '/build/libass/src/libass'
libass: Neither PlayResX nor PlayResY defined. Assuming 384x288
PASS: checkasm/checkasm
============================================================================
Testsuite summary for libass 0.17.1
============================================================================
# TOTAL: 1
# PASS:  1
# SKIP:  0
# XFAIL: 0
# FAIL:  0
# XPASS: 0
# ERROR: 0
============================================================================
make[2]: Leaving directory '/build/libass/src/libass'
make[1]: Leaving directory '/build/libass/src/libass'
Loading font 'DejaVuSans.ttf'.
Processing 'ffmpeg.ass':
  Time 0:00:08.000 - 0.000 SAME
Processing 'ffmpeg_legacy2.ass':
  Time 0:00:08.000 - 0.000 SAME
Processing 'ffmpeg_legacy2+sbas.ass':
  Time 0:00:08.000 - 0.000 SAME
Processing 'ffmpeg_legacy3.ass':
  Time 0:00:08.000 - 0.000 SAME
Processing 'ffmpeg_legacy4.ass':
  Time 0:00:08.000 - 0.000 SAME
Processing 'not-ffmpeg.ass':
  Time 0:00:08.000 - 0.000 SAME
All 6 images have passed test (BAD or better)

All tests passed!
```

**Comment by TheOneric** [comment]
Thanks!

**Pull request merged**
