### PR TITLE
Use FriBiDi 1.x API when available

### PR DESCRIPTION
**Pull request by khaledhosny**
This allows making use of the updated UBA in Unicode 6.3 and up.

### CODE REVIEW

**Comment by wm4** [comment]
On the first looks this seems reasonable, but I can't comment on the actual code.
What worries me a bit is the ifdeffery, but probably unavoidable since it'll take a long time until we can make newer fribidi a hard dependency.

**Comment by khaledhosny** [comment]
Ping

**Comment by astiob** [comment]
Hey, I’m terribly sorry for the lack of response. I was originally going to merge this immediately after merging #285, but it’s taken me crazy long to review that. Is this still relevant? If so, I’m definitely still interested in merging this.

**Comment by astiob** [comment]
Finally merged this as df7c00c95ec6e526bf85e6bc8296eaca66f5db8d.

**Pull request closed without merging**
